### ISSUE TITLE
Related Lists doesn't reflect REST API specification.

### ISSUE THREAD

**Issue by gmcnicol** [zoho/zohocrm-javascript-sdk-6.0#4]
When creating a new RelatedListOperations object, the SDK requires you to set a layout ID. This is not a requirement of the REST API, where the required argument is the module name. The Standard layout for that module should be used by default.

There is no way to specify the module name at all.

**Comment by raja-k-7453** [comment]
Thanks, @gmcnicol for your contribution. Please refer to this [sample code](https://github.com/zoho/zohocrm-javascript-sdk-6.0/tree/master/samples/related_lists) for RelatedList Operations.

**Comment by gmcnicol** [comment]
@raja-7453 this raises more questions:

How did you get the magic string for the layout ID? 
Why is it mandatory when it isn't in the REST API? 

This is still a bug, even in 2.0.

**Comment by raja-k-7453** [comment]
@gmcnicol  In both the getRelatedLists and getRelatedList methods, the layout ID is common,  and included as a parameter in the class [constructor](https://github.com/zoho/zohocrm-javascript-sdk-6.0/blob/9b9fb16ddf1777c7028175100bc1e20bdcdb57bb/src/com/zoho/crm/api/related_lists/related_list.js#L844). Please note that the Layout ID is optional, as demonstrated in the provided [sample code](https://github.com/zoho/zohocrm-javascript-sdk-6.0/tree/master/samples/related_lists). This applies to both versions, v1.0.0 and v2.0.0. Could you please specify where you found that the Layout ID is a mandatory parameter?

We are currently updating the sample codes for all methods, and they will be published soon. However, as you had specific concerns regarding these methods, we have prioritized and updated the sample codes for these methods alone at this time.

**Comment by gmcnicol** [comment]
Thanks. This was a 100% skill issue on my part. 

All resolved.
