### ISSUE TITLE
Button to send a message on CLIQ missing.

### ISSUE THREAD

**Issue by ayush-021trade** [zoho/zohocrm-javascript-sdk-6.0#8]
If i person is using CLIQ web, there is no chance he/she can send a message purely using mouse. 
A keyboard is must to hit an enter. 
A button to send a message should be there to ease the process.

**Comment by raja-k-7453** [comment]
Hi @ayush-021trade,  Kindly forward the details of the use case to [support@zohocliq.com](support@zohocliq.com)
